export const LOAD_PRODUCTS_COLLECTION_SUCCESS = 'LOAD_PRODUCTS_COLLECTION_SUCCESS';
export const LOAD_PRODUCT = 'LOAD_PRODUCT';
export const CHANGE_PRODUCT_DETAIL = 'CHANGE_PRODUCT_DETAIL';
export const MOVE_PRODUCTS_SLIDER = 'MOVE_PRODUCTS_SLIDER';
export const SHOW_TOP_PRODUCTS_WIDGET = 'SHOW_TOP_PRODUCTS_WIDGET';
export const THROW_APP_ERROR = 'THROW_APP_ERROR';
